import {
  Cnpj,
  Banco,
  ContaBancaria,
  Categoria,
  ContaContabil,
  Movimentacao,
  Regra,
  ArquivoOFX,
} from '@/types';

export const CNPJS: Cnpj[] = [
  {
    id: 'geral',
    nomeFantasia: 'Geral',
    razao: 'Visão consolidada do grupo',
    cnpj: null,
    tag: 'GERAL',
  },
  {
    id: 'procare',
    nomeFantasia: 'Procare Serviços',
    razao: 'PROCARE SERVIÇOS LTDA',
    cnpj: '12.345.678/0001-90',
    regime: 'Lucro Real',
    tag: 'PRC',
    status: 'ok',
  },
  {
    id: 'newland',
    nomeFantasia: 'Newland Participações',
    razao: 'NEWLAND PARTICIPAÇÕES LTDA',
    cnpj: '98.765.432/0001-10',
    regime: 'Lucro Real',
    tag: 'NWL',
    status: 'ok',
  },
  {
    id: 'procare-filial',
    nomeFantasia: 'Procare Filial SP',
    razao: 'PROCARE SERVIÇOS LTDA — FILIAL',
    cnpj: '12.345.678/0002-71',
    regime: 'Lucro Real',
    tag: 'PRC02',
    status: 'warn',
  },
  {
    id: 'tecnoflora',
    nomeFantasia: 'Tecnoflora Comércio',
    razao: 'TECNOFLORA COMÉRCIO E IMPORTAÇÃO LTDA',
    cnpj: '45.123.987/0001-22',
    regime: 'Lucro Presumido',
    tag: 'TCF',
    status: 'ok',
  },
  {
    id: 'holding-nm',
    nomeFantasia: 'NM Holding',
    razao: 'NM HOLDING ADMINISTRAÇÃO E PARTICIPAÇÕES S.A.',
    cnpj: '33.999.111/0001-05',
    regime: 'Lucro Real',
    tag: 'NMH',
    status: 'ok',
  },
  {
    id: 'agro-bonsucesso',
    nomeFantasia: 'Agro Bonsucesso',
    razao: 'AGROPECUÁRIA BONSUCESSO LTDA',
    cnpj: '27.554.300/0001-48',
    regime: 'Lucro Real',
    tag: 'AGB',
    status: 'err',
  },
];

export const BANCOS: Banco[] = [
  { id: 'itau', nome: 'Itaú Unibanco', codigo: '341', cor: '#EC7000' },
  { id: 'bradesco', nome: 'Bradesco', codigo: '237', cor: '#CC092F' },
  { id: 'bb', nome: 'Banco do Brasil', codigo: '001', cor: '#F8C300' },
  { id: 'santander', nome: 'Santander', codigo: '033', cor: '#EC0000' },
  { id: 'caixa', nome: 'Caixa Econômica', codigo: '104', cor: '#0070AF' },
  { id: 'sicredi', nome: 'Sicredi', codigo: '748', cor: '#3FA535' },
  { id: 'inter', nome: 'Inter', codigo: '077', cor: '#FF7A00' },
];

export const CONTAS_BANCARIAS: ContaBancaria[] = [
  {
    id: 'cb1',
    cnpjId: 'procare',
    bancoId: 'itau',
    agencia: '0145',
    conta: '12345-6',
    apelido: 'Itaú — Movimento',
    tipo: 'Conta Corrente',
    saldo: 487329.42,
    ativo: true,
  },
  {
    id: 'cb2',
    cnpjId: 'procare',
    bancoId: 'bradesco',
    agencia: '2280',
    conta: '98765-1',
    apelido: 'Bradesco — Pagamento',
    tipo: 'Conta Corrente',
    saldo: 132450.18,
    ativo: true,
  },
  {
    id: 'cb3',
    cnpjId: 'newland',
    bancoId: 'itau',
    agencia: '0145',
    conta: '54321-0',
    apelido: 'Itaú — Investimentos',
    tipo: 'Conta Corrente',
    saldo: 1245680.0,
    ativo: true,
  },
  {
    id: 'cb4',
    cnpjId: 'newland',
    bancoId: 'santander',
    agencia: '1832',
    conta: '00112-3',
    apelido: 'Santander — Holding',
    tipo: 'Conta Corrente',
    saldo: 89234.55,
    ativo: true,
  },
  {
    id: 'cb5',
    cnpjId: 'tecnoflora',
    bancoId: 'bb',
    agencia: '3045',
    conta: '44781-2',
    apelido: 'BB — Operacional',
    tipo: 'Conta Corrente',
    saldo: 234518.9,
    ativo: true,
  },
  {
    id: 'cb6',
    cnpjId: 'holding-nm',
    bancoId: 'sicredi',
    agencia: '0301',
    conta: '70010-9',
    apelido: 'Sicredi — Caixa Holding',
    tipo: 'Conta Corrente',
    saldo: 678900.12,
    ativo: true,
  },
  {
    id: 'cb7',
    cnpjId: 'agro-bonsucesso',
    bancoId: 'caixa',
    agencia: '1244',
    conta: '00891-5',
    apelido: 'Caixa — Rural',
    tipo: 'Conta Corrente',
    saldo: 45219.3,
    ativo: false,
  },
];

export const CATEGORIAS: Categoria[] = [
  {
    id: 'c1',
    nome: 'Aluguel',
    tipo: 'despesa',
    cnpjId: '*',
    contaDebId: 'd-aluguel',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 8,
  },
  {
    id: 'c2',
    nome: 'Energia Elétrica',
    tipo: 'despesa',
    cnpjId: '*',
    contaDebId: 'd-energia',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 12,
  },
  {
    id: 'c3',
    nome: 'Folha de Pagamento',
    tipo: 'despesa',
    cnpjId: '*',
    contaDebId: 'd-folha',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 24,
  },
  {
    id: 'c4',
    nome: 'Honorários Contábeis',
    tipo: 'despesa',
    cnpjId: '*',
    contaDebId: 'd-honor',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 5,
  },
  {
    id: 'c5',
    nome: 'Tarifas Bancárias',
    tipo: 'despesa',
    cnpjId: '*',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 47,
  },
  {
    id: 'c6',
    nome: 'Impostos Federais — DARF',
    tipo: 'imposto',
    cnpjId: '*',
    contaDebId: 'd-imp-fed',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 14,
  },
  {
    id: 'c7',
    nome: 'Impostos Municipais — ISS',
    tipo: 'imposto',
    cnpjId: '*',
    contaDebId: 'd-imp-mun',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 6,
  },
  {
    id: 'c8',
    nome: 'FGTS',
    tipo: 'imposto',
    cnpjId: '*',
    contaDebId: 'd-fgts',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 9,
  },
  {
    id: 'c9',
    nome: 'Fornecedores — Insumos',
    tipo: 'despesa',
    cnpjId: '*',
    contaDebId: 'd-fornec',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 38,
  },
  {
    id: 'c10',
    nome: 'Clientes — Recebimentos',
    tipo: 'receita',
    cnpjId: '*',
    contaDebId: 'c-banco-mov',
    contaCredId: 'c-clientes',
    ativo: true,
    ops: 72,
  },
  {
    id: 'c11',
    nome: 'Empréstimos — Captação',
    tipo: 'outro',
    cnpjId: '*',
    contaDebId: 'c-banco-mov',
    contaCredId: 'c-emp',
    ativo: true,
    ops: 2,
  },
  {
    id: 'c12',
    nome: 'Transferência entre Contas',
    tipo: 'transferencia',
    cnpjId: '*',
    contaDebId: 'c-banco-trans',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 21,
  },
  {
    id: 'c13',
    nome: 'Distribuição de Lucros',
    tipo: 'outro',
    cnpjId: 'newland',
    contaDebId: 'd-distrib',
    contaCredId: 'c-banco-mov',
    ativo: true,
    ops: 3,
  },
  {
    id: 'c14',
    nome: 'Aporte de Capital',
    tipo: 'outro',
    cnpjId: '*',
    contaDebId: 'c-banco-mov',
    contaCredId: 'c-aporte',
    ativo: false,
    ops: 0,
  },
  {
    id: 'c15',
    nome: 'Recebimento PIX — Clientes',
    tipo: 'receita',
    cnpjId: '*',
    contaDebId: 'c-banco-mov',
    contaCredId: 'c-clientes',
    ativo: true,
    ops: 58,
  },
];

export const CONTAS_CONTABEIS: ContaContabil[] = [
  {
    id: 'd-aluguel',
    codigo: '4.1.1.02',
    nome: 'Despesas com Aluguel',
    natureza: 'debito',
    tipo: 'Despesa Operacional',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-energia',
    codigo: '4.1.1.05',
    nome: 'Despesas com Energia',
    natureza: 'debito',
    tipo: 'Despesa Operacional',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-folha',
    codigo: '4.1.2.01',
    nome: 'Salários e Ordenados',
    natureza: 'debito',
    tipo: 'Pessoal',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-honor',
    codigo: '4.1.3.04',
    nome: 'Honorários Contábeis',
    natureza: 'debito',
    tipo: 'Despesa Operacional',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-tarifas',
    codigo: '4.1.4.01',
    nome: 'Despesas Bancárias',
    natureza: 'debito',
    tipo: 'Despesa Financeira',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-imp-fed',
    codigo: '4.2.1.01',
    nome: 'Impostos Federais',
    natureza: 'debito',
    tipo: 'Tributos',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-imp-mun',
    codigo: '4.2.2.01',
    nome: 'Impostos Municipais',
    natureza: 'debito',
    tipo: 'Tributos',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-fgts',
    codigo: '4.1.2.05',
    nome: 'FGTS a Recolher',
    natureza: 'debito',
    tipo: 'Pessoal',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-fornec',
    codigo: '2.1.1.01',
    nome: 'Fornecedores Diversos',
    natureza: 'debito',
    tipo: 'Passivo Circulante',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'd-distrib',
    codigo: '2.3.1.01',
    nome: 'Distribuição de Lucros',
    natureza: 'debito',
    tipo: 'Patrimônio',
    cnpjId: 'newland',
    ativo: true,
  },
  {
    id: 'c-banco-mov',
    codigo: '1.1.1.02',
    nome: 'Banco Conta Movimento',
    natureza: 'credito',
    tipo: 'Disponível',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'c-banco-trans',
    codigo: '1.1.1.03',
    nome: 'Banco — Transferências',
    natureza: 'credito',
    tipo: 'Disponível',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'c-clientes',
    codigo: '3.1.1.01',
    nome: 'Receita Bruta — Serviços',
    natureza: 'credito',
    tipo: 'Receita',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'c-emp',
    codigo: '2.2.1.01',
    nome: 'Empréstimos a Pagar',
    natureza: 'credito',
    tipo: 'Passivo Não Circ.',
    cnpjId: '*',
    ativo: true,
  },
  {
    id: 'c-aporte',
    codigo: '2.3.2.01',
    nome: 'Aporte de Capital',
    natureza: 'credito',
    tipo: 'Patrimônio',
    cnpjId: '*',
    ativo: true,
  },
];

export const REGRAS: Regra[] = [
  {
    id: 'r1',
    nome: 'Tarifa Bancária — Itaú',
    cnpjId: '*',
    contaBancariaId: '*',
    keywords: ['TARIFA BANCARIA', 'TAR PAC', 'TARIFA PACOTE'],
    tipoMov: 'debito',
    valorMin: 0,
    valorMax: 200,
    periodicidade: 'mensal',
    categoriaId: 'c5',
    confianca: 96,
    ativo: true,
    hits: 47,
  },
  {
    id: 'r2',
    nome: 'DARF — Federais',
    cnpjId: '*',
    contaBancariaId: '*',
    keywords: ['DARF', 'RECEITA FEDERAL', 'DCTFWEB'],
    tipoMov: 'debito',
    valorMin: 0,
    valorMax: null,
    periodicidade: 'mensal',
    categoriaId: 'c6',
    confianca: 94,
    ativo: true,
    hits: 14,
  },
  {
    id: 'r3',
    nome: 'Folha de Pagamento — Mensal',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    keywords: ['FOLHA', 'SALARIO', 'PAGAMENTO FUNC'],
    tipoMov: 'debito',
    valorMin: 1000,
    valorMax: null,
    periodicidade: 'mensal',
    categoriaId: 'c3',
    confianca: 91,
    ativo: true,
    hits: 24,
  },
  {
    id: 'r4',
    nome: 'FGTS — GRF',
    cnpjId: '*',
    contaBancariaId: '*',
    keywords: ['FGTS', 'GRF CAIXA', 'GUIA FGTS'],
    tipoMov: 'debito',
    valorMin: 0,
    valorMax: null,
    periodicidade: 'mensal',
    categoriaId: 'c8',
    confianca: 95,
    ativo: true,
    hits: 9,
  },
  {
    id: 'r5',
    nome: 'PIX Recebido — Clientes',
    cnpjId: '*',
    contaBancariaId: '*',
    keywords: ['PIX RECEBIDO', 'CREDITO PIX', 'QR PIX'],
    tipoMov: 'credito',
    valorMin: 0,
    valorMax: null,
    periodicidade: 'diaria',
    categoriaId: 'c15',
    confianca: 78,
    ativo: true,
    hits: 58,
  },
  {
    id: 'r6',
    nome: 'Aluguel — Recorrente',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    keywords: ['ALUGUEL', 'LOCACAO'],
    tipoMov: 'debito',
    valorMin: 3000,
    valorMax: 12000,
    periodicidade: 'mensal',
    categoriaId: 'c1',
    confianca: 88,
    ativo: true,
    hits: 8,
  },
  {
    id: 'r7',
    nome: 'Transferência Entre Contas',
    cnpjId: '*',
    contaBancariaId: '*',
    keywords: ['TED', 'TRANSFER INTERNA', 'MESMA TITULARIDADE'],
    tipoMov: 'ambos',
    valorMin: 0,
    valorMax: null,
    periodicidade: 'variavel',
    categoriaId: 'c12',
    confianca: 82,
    ativo: false,
    hits: 21,
  },
];

export const MOVIMENTACOES: Movimentacao[] = [
  {
    id: 'm001',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '14/05/2026',
    tipo: 'debito',
    valor: 4500.0,
    descricaoOFX: 'ALUGUEL LOJA AV PAULISTA - LOCATARIO IMOVEIS LTDA',
    categoria: 'Aluguel',
    categoriaId: 'c1',
    contaDebId: 'd-aluguel',
    contaCredId: 'c-banco-mov',
    status: 'conciliado',
    regraId: 'r6',
    confianca: 92,
    doc: '789045',
    usuario: 'Beatriz L.',
    hora: '08:42',
  },
  {
    id: 'm002',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '14/05/2026',
    tipo: 'debito',
    valor: 38.9,
    descricaoOFX: 'TARIFA BANCARIA - PACOTE DE SERVICOS',
    status: 'sugerido',
    regraId: 'r1',
    categoriaId: 'c5',
    categoria: 'Tarifas Bancárias',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    confianca: 96,
    doc: '001',
    usuario: null,
    hora: null,
  },
  {
    id: 'm003',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '13/05/2026',
    tipo: 'credito',
    valor: 12450.0,
    descricaoOFX: 'PIX RECEBIDO - TECNOSOFT SOLUCOES LTDA - NF 4521',
    status: 'conciliado',
    regraId: 'r5',
    categoriaId: 'c15',
    categoria: 'Recebimento PIX — Clientes',
    contaDebId: 'c-banco-mov',
    contaCredId: 'c-clientes',
    confianca: 89,
    doc: 'NF4521',
    usuario: 'Beatriz L.',
    hora: '11:15',
  },
  {
    id: 'm004',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '13/05/2026',
    tipo: 'debito',
    valor: 8765.4,
    descricaoOFX: 'DARF - COD 1708 - IRPJ APURACAO MENSAL',
    status: 'sugerido',
    regraId: 'r2',
    categoriaId: 'c6',
    categoria: 'Impostos Federais — DARF',
    contaDebId: 'd-imp-fed',
    contaCredId: 'c-banco-mov',
    confianca: 94,
    doc: 'DARF1708',
    usuario: null,
    hora: null,
  },
  {
    id: 'm005',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '13/05/2026',
    tipo: 'debito',
    valor: 24890.3,
    descricaoOFX: 'PAGAMENTO FORN - INSUMOS RAPIDOS COMERCIO LTDA',
    status: 'pendente',
    categoria: null,
    doc: '5781',
    usuario: null,
    hora: null,
  },
  {
    id: 'm006',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '12/05/2026',
    tipo: 'debito',
    valor: 32.5,
    descricaoOFX: 'TAR PAC SERVICOS - MAIO/2026',
    status: 'sugerido',
    regraId: 'r1',
    categoriaId: 'c5',
    categoria: 'Tarifas Bancárias',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    confianca: 96,
    doc: '002',
    usuario: null,
    hora: null,
  },
  {
    id: 'm007',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '12/05/2026',
    tipo: 'credito',
    valor: 5800.0,
    descricaoOFX: 'PIX RECEBIDO - JOAO CARLOS MENDES - PROPOSTA 22',
    status: 'pendente',
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm008',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '12/05/2026',
    tipo: 'debito',
    valor: 87340.0,
    descricaoOFX: 'FOLHA PAGAMENTO - COMPETENCIA ABRIL/2026 - 24 FUNC',
    status: 'conciliado',
    regraId: 'r3',
    categoriaId: 'c3',
    categoria: 'Folha de Pagamento',
    contaDebId: 'd-folha',
    contaCredId: 'c-banco-mov',
    confianca: 91,
    doc: 'FOLHA04-26',
    usuario: 'Carlos M.',
    hora: '16:08',
  },
  {
    id: 'm009',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '11/05/2026',
    tipo: 'debito',
    valor: 6234.78,
    descricaoOFX: 'GRF CAIXA - FGTS COMPETENCIA 04/2026',
    status: 'conciliado',
    regraId: 'r4',
    categoriaId: 'c8',
    categoria: 'FGTS',
    contaDebId: 'd-fgts',
    contaCredId: 'c-banco-mov',
    confianca: 95,
    doc: 'GRF042026',
    usuario: 'Carlos M.',
    hora: '10:22',
  },
  {
    id: 'm010',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '11/05/2026',
    tipo: 'credito',
    valor: 22500.0,
    descricaoOFX: 'DOC RECEBIDO - PROCARE NEWLAND SERVICOS - DOC 145',
    status: 'divergente',
    doc: 'DOC145',
    usuario: 'Ana P.',
    hora: '14:50',
  },
  {
    id: 'm011',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '10/05/2026',
    tipo: 'debito',
    valor: 1238.45,
    descricaoOFX: 'ENERGIA ELETRICA - ENEL DISTRIBUICAO SP - REF 04/26',
    status: 'conciliado',
    categoriaId: 'c2',
    categoria: 'Energia Elétrica',
    contaDebId: 'd-energia',
    contaCredId: 'c-banco-mov',
    confianca: 90,
    doc: 'ENEL0426',
    usuario: 'Beatriz L.',
    hora: '09:11',
  },
  {
    id: 'm012',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '10/05/2026',
    tipo: 'debito',
    valor: 1850.0,
    descricaoOFX: 'HONORARIOS - ESCRITORIO SILVA E ALMEIDA CONTABEIS',
    status: 'pendente',
    doc: '5901',
    usuario: null,
    hora: null,
  },
  {
    id: 'm013',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '09/05/2026',
    tipo: 'debito',
    valor: 450.0,
    descricaoOFX: 'DAS-MEI - PAGAMENTO MENSAL SIMPLES',
    status: 'revisar',
    doc: 'DASMEI',
    usuario: null,
    hora: null,
  },
  {
    id: 'm014',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '09/05/2026',
    tipo: 'credito',
    valor: 18900.0,
    descricaoOFX: 'PIX RECEBIDO - METALURGICA CAMPINAS LTDA - SERVICO MAIO',
    status: 'sugerido',
    regraId: 'r5',
    categoriaId: 'c15',
    categoria: 'Recebimento PIX — Clientes',
    contaDebId: 'c-banco-mov',
    contaCredId: 'c-clientes',
    confianca: 78,
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm015',
    cnpjId: 'procare',
    contaBancariaId: 'cb1',
    data: '08/05/2026',
    tipo: 'debito',
    valor: 75.0,
    descricaoOFX: 'BOLETO LIQUIDADO - ASSOCIACAO COMERCIAL SP',
    status: 'ignorado',
    doc: 'BLT77',
    usuario: 'Carlos M.',
    hora: '17:33',
  },
  {
    id: 'm016',
    cnpjId: 'procare',
    contaBancariaId: 'cb2',
    data: '14/05/2026',
    tipo: 'debito',
    valor: 5234.1,
    descricaoOFX: 'TED ENVIADO - PROCARE SERVICOS LTDA - MESMA TITULARIDADE',
    status: 'sugerido',
    regraId: 'r7',
    categoriaId: 'c12',
    categoria: 'Transferência entre Contas',
    contaDebId: 'c-banco-trans',
    contaCredId: 'c-banco-mov',
    confianca: 82,
    doc: 'TED881',
    usuario: null,
    hora: null,
  },
  {
    id: 'm017',
    cnpjId: 'procare',
    contaBancariaId: 'cb2',
    data: '13/05/2026',
    tipo: 'debito',
    valor: 28.5,
    descricaoOFX: 'TARIFA BANCARIA - MANUTENCAO CONTA',
    status: 'conciliado',
    regraId: 'r1',
    categoriaId: 'c5',
    categoria: 'Tarifas Bancárias',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    confianca: 96,
    doc: '003',
    usuario: 'Beatriz L.',
    hora: '08:50',
  },
  {
    id: 'm018',
    cnpjId: 'newland',
    contaBancariaId: 'cb3',
    data: '14/05/2026',
    tipo: 'credito',
    valor: 180000.0,
    descricaoOFX: 'RESGATE CDB ITAU - APLICACAO 04/2025',
    status: 'pendente',
    doc: 'CDB991',
    usuario: null,
    hora: null,
  },
  {
    id: 'm019',
    cnpjId: 'newland',
    contaBancariaId: 'cb3',
    data: '13/05/2026',
    tipo: 'debito',
    valor: 95000.0,
    descricaoOFX: 'DISTRIBUICAO DE LUCROS - SOCIO 1 - REF ABR/26',
    status: 'conciliado',
    categoriaId: 'c13',
    categoria: 'Distribuição de Lucros',
    contaDebId: 'd-distrib',
    contaCredId: 'c-banco-mov',
    confianca: 100,
    doc: 'DL0426',
    usuario: 'Ana P.',
    hora: '15:02',
  },
  {
    id: 'm020',
    cnpjId: 'newland',
    contaBancariaId: 'cb3',
    data: '12/05/2026',
    tipo: 'debito',
    valor: 4350.0,
    descricaoOFX: 'DARF - COD 5952 - IRRF SOBRE LUCROS',
    status: 'sugerido',
    regraId: 'r2',
    categoriaId: 'c6',
    categoria: 'Impostos Federais — DARF',
    contaDebId: 'd-imp-fed',
    contaCredId: 'c-banco-mov',
    confianca: 94,
    doc: 'DARF5952',
    usuario: null,
    hora: null,
  },
  {
    id: 'm021',
    cnpjId: 'newland',
    contaBancariaId: 'cb3',
    data: '11/05/2026',
    tipo: 'debito',
    valor: 42.0,
    descricaoOFX: 'TARIFA PACOTE DE SERVICOS - MAIO/2026',
    status: 'sugerido',
    regraId: 'r1',
    categoriaId: 'c5',
    categoria: 'Tarifas Bancárias',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    confianca: 96,
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm022',
    cnpjId: 'newland',
    contaBancariaId: 'cb3',
    data: '10/05/2026',
    tipo: 'credito',
    valor: 28400.0,
    descricaoOFX: 'TED RECEBIDO - PROCARE SERVICOS LTDA - APORTE OP',
    status: 'divergente',
    doc: 'TED7711',
    usuario: 'Ana P.',
    hora: '09:48',
  },
  {
    id: 'm023',
    cnpjId: 'newland',
    contaBancariaId: 'cb4',
    data: '14/05/2026',
    tipo: 'debito',
    valor: 850.0,
    descricaoOFX: 'HONORARIOS - PRESTACAO SERVICOS CONTABEIS',
    status: 'pendente',
    doc: 'HON882',
    usuario: null,
    hora: null,
  },
  {
    id: 'm024',
    cnpjId: 'newland',
    contaBancariaId: 'cb4',
    data: '13/05/2026',
    tipo: 'debito',
    valor: 35.0,
    descricaoOFX: 'TAR PAC SERV - MANUTENCAO',
    status: 'sugerido',
    regraId: 'r1',
    categoriaId: 'c5',
    categoria: 'Tarifas Bancárias',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    confianca: 96,
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm025',
    cnpjId: 'tecnoflora',
    contaBancariaId: 'cb5',
    data: '14/05/2026',
    tipo: 'credito',
    valor: 67200.0,
    descricaoOFX: 'PIX RECEBIDO - VARIOS CLIENTES - VENDAS MAIO',
    status: 'pendente',
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm026',
    cnpjId: 'tecnoflora',
    contaBancariaId: 'cb5',
    data: '13/05/2026',
    tipo: 'debito',
    valor: 12500.0,
    descricaoOFX: 'PAGAMENTO IMPORTACAO - FOB ITEM 22 - INVOICE 8821',
    status: 'revisar',
    doc: 'INV8821',
    usuario: null,
    hora: null,
  },
  {
    id: 'm027',
    cnpjId: 'tecnoflora',
    contaBancariaId: 'cb5',
    data: '12/05/2026',
    tipo: 'debito',
    valor: 4830.2,
    descricaoOFX: 'DCTFWEB - DEBITOS APURADOS COMP 04/26',
    status: 'sugerido',
    regraId: 'r2',
    categoriaId: 'c6',
    categoria: 'Impostos Federais — DARF',
    contaDebId: 'd-imp-fed',
    contaCredId: 'c-banco-mov',
    confianca: 94,
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm028',
    cnpjId: 'holding-nm',
    contaBancariaId: 'cb6',
    data: '14/05/2026',
    tipo: 'credito',
    valor: 1200000.0,
    descricaoOFX: 'RECEBIMENTO - DIVIDENDOS CONTROLADAS',
    status: 'conciliado',
    categoria: 'Dividendos',
    confianca: 100,
    doc: 'DIV12',
    usuario: 'Ana P.',
    hora: '10:15',
  },
  {
    id: 'm029',
    cnpjId: 'holding-nm',
    contaBancariaId: 'cb6',
    data: '12/05/2026',
    tipo: 'debito',
    valor: 250000.0,
    descricaoOFX: 'DISTRIBUICAO DE LUCROS - HOLDING NM - SOCIOS',
    status: 'pendente',
    doc: null,
    usuario: null,
    hora: null,
  },
  {
    id: 'm030',
    cnpjId: 'holding-nm',
    contaBancariaId: 'cb6',
    data: '11/05/2026',
    tipo: 'debito',
    valor: 65.0,
    descricaoOFX: 'TARIFA BANCARIA - PACOTE PREMIUM',
    status: 'sugerido',
    regraId: 'r1',
    categoriaId: 'c5',
    categoria: 'Tarifas Bancárias',
    contaDebId: 'd-tarifas',
    contaCredId: 'c-banco-mov',
    confianca: 96,
    doc: null,
    usuario: null,
    hora: null,
  },
];

export const ARQUIVOS_OFX: ArquivoOFX[] = [
  {
    id: 'f1',
    nome: 'extrato_itau_procare_2026_05.ofx',
    contaBancariaId: 'cb1',
    periodo: '01/05 — 14/05',
    movimentos: 87,
    dataImport: '14/05/2026 09:12',
    usuario: 'Beatriz L.',
    status: 'processado',
  },
  {
    id: 'f2',
    nome: 'extrato_bradesco_procare_05.ofx',
    contaBancariaId: 'cb2',
    periodo: '01/05 — 14/05',
    movimentos: 22,
    dataImport: '14/05/2026 09:14',
    usuario: 'Beatriz L.',
    status: 'processado',
  },
  {
    id: 'f3',
    nome: 'extrato_itau_newland_05.ofx',
    contaBancariaId: 'cb3',
    periodo: '01/05 — 14/05',
    movimentos: 38,
    dataImport: '14/05/2026 09:20',
    usuario: 'Ana P.',
    status: 'processado',
  },
  {
    id: 'f4',
    nome: 'extrato_santander_newland_05.ofx',
    contaBancariaId: 'cb4',
    periodo: '01/05 — 14/05',
    movimentos: 12,
    dataImport: '14/05/2026 09:21',
    usuario: 'Ana P.',
    status: 'processado',
  },
  {
    id: 'f5',
    nome: 'extrato_bb_tecnoflora_05.ofx',
    contaBancariaId: 'cb5',
    periodo: '01/05 — 12/05',
    movimentos: 41,
    dataImport: '13/05/2026 17:50',
    usuario: 'Carlos M.',
    status: 'processado',
  },
  {
    id: 'f6',
    nome: 'extrato_sicredi_holding_05.ofx',
    contaBancariaId: 'cb6',
    periodo: '01/05 — 14/05',
    movimentos: 7,
    dataImport: '14/05/2026 09:30',
    usuario: 'Ana P.',
    status: 'processado',
  },
];

export const STATUSES = {
  pendente: { label: 'Pendente', color: 'amber' },
  sugerido: { label: 'Sugerido', color: 'blue' },
  conciliado: { label: 'Conciliado', color: 'green' },
  divergente: { label: 'Divergente', color: 'red' },
  ignorado: { label: 'Ignorado', color: 'gray' },
  revisar: { label: 'Revisar', color: 'violet' },
} as const;

export const USUARIO_LOGADO = { nome: 'Beatriz Lemos', role: 'Contadora', iniciais: 'BL' };

export function fmtMoney(n: number | null | undefined): string {
  const v = n == null ? 0 : n;
  return v.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
